name: validate

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:

  validate:
    runs-on: ubuntu-latest
    env:
      SNOWPLOW_CONSOLE_ORG_ID: 782acb70-b482-4906-b223-159f51068f22
      SNOWPLOW_CONSOLE_API_KEY_ID: ${{ secrets.SNOWPLOW_CONSOLE_API_KEY_ID }}
      SNOWPLOW_CONSOLE_API_KEY: ${{ secrets.SNOWPLOW_CONSOLE_API_KEY_SECRET }}

    steps:
      - uses: actions/checkout@v4
      - uses: snowplow-product/setup-snowplow-cli@v1

      - name: validate
        run: snowplow-cli ds validate data-structures --gh-annotate
